### ISSUE TITLE
sorting paging not working with LitElement

### ISSUE THREAD

**Issue by Pankraz76** [ExmgElements/exmg-paper-datatable#4]
Thanks for the nice component, glat to found this one as its the only one supporting polymer 3.0 atm imho.

The table gets rendered fine, but I have an issue with the sorting paging feature. I´ve checked with demo outputs that the data and stuff gets set correctly it seems to be, but unfortunately the sorting paging is not working at all.

Would you please have a look? thanks a lot.

![image](https://user-images.githubusercontent.com/8830888/44336916-3e6b0800-a479-11e8-9cb2-10c8cf4479bd.png)

**Comment by marksmits** [comment]
I think it would be possible to rewrite sorting/paging and filter elements to work with events instead of two way bindings. But i think you probably would be better off just creating a set of elements match more with the lit-element way. 

So for now just stick with p3 PolymerElement if you want to use this table ;-)
